services:
  - type: web
    name: projeto3-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && mkdir -p downloads && if [ -f ../Projeto3-Desktop/dist/VERIFIQ.exe ]; then cp ../Projeto3-Desktop/dist/VERIFIQ.exe downloads/VERIFIQ.exe; fi"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
